<?php

namespace AppBundle\Repository;

/**
 * commodityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commodityRepository extends \Doctrine\ORM\EntityRepository
{
}
