<?php

namespace AppBundle\Repository;

/**
 * MarketerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketerRepository extends \Doctrine\ORM\EntityRepository
{
}
